invisible({
   plutil::mysource(ursa)
   session_grid(NULL)
   require(methods)
   a <- ursa_dummy(mul=1/16)
   print(a)
   a <- a[a>100]
   fname <- tempfile()
   b1 <- polygonize(a,fname)
   list1 <- dir(path=dirname(fname),pattern=basename(fname),full.names=TRUE)
   print(list1)
   file.remove(list1)
   b2 <- polygonize(a)
   print(band_mean(a))
   print(apply(b2@data,2,mean,na.rm=TRUE))
   print(with(ursa_grid(a),array(c(minx,miny,maxx,maxy),dim=c(2,2)
                                ,dimnames=list(c("x","y"),c("min","max")))))
   print(b2@bbox)
})
